"""질문 이해와 rewrite 정책의 공개 허브.

실제 구현은 intents/rewrite/ambiguity/decompose로 분리하고,
바깥 import 경로는 이 파일에서 계속 유지한다.
"""

from __future__ import annotations

from .corpus_scope import detect_out_of_corpus_version, detect_unsupported_product
from .followups import has_corrective_follow_up, has_follow_up_reference
from .text_utils import contains_hangul
from .rewrite import (
    has_explicit_topic_signal,
    needs_rewrite,
    normalize_query,
    query_book_adjustments,
    rewrite_query,
)
from .intents import (
    APP_RE,
    ARCHITECTURE_RE,
    AUDIT_RE,
    AUTH_RE,
    AUTHZ_RE,
    BACKUP_RE,
    CERT_RE,
    CLUSTER_ADMIN_RE,
    COMPARE_DECOMPOSE_RE,
    COMPARE_RE,
    CONJUNCTION_SPLIT_RE,
    CRASH_LOOP_RE,
    DEPLOYMENTCONFIG_RE,
    DEPLOYMENT_RE,
    DISCONNECTED_RE,
    DOC_LOCATOR_RE,
    DRAIN_RE,
    EDIT_ROLE_RE,
    ETCD_RE,
    EVENT_RE,
    EXPIRY_RE,
    EXPLAINER_RE,
    FINALIZER_RE,
    GENERIC_CONTEXT_TOPIC_RE,
    GENERIC_INTRO_RE,
    HOSTED_CONTROL_PLANE_RE,
    INFRA_RE,
    INGRESS_RE,
    KUBERNETES_RE,
    LOGGING_RE,
    MACHINE_CONFIG_REBOOT_RE,
    MCO_RE,
    MONITORING_RE,
    NODE_NOTREADY_RE,
    NODE_RE,
    OC_LOGIN_RE,
    OCP_RE,
    OPENSHIFT_RE,
    OPERATOR_RE,
    POD_LIFECYCLE_RE,
    POD_PENDING_RE,
    PROJECT_SCOPE_RE,
    PROJECT_TERMINATING_RE,
    REMAINING_RESOURCE_RE,
    REPLICA_RE,
    RBAC_RE,
    ROLE_API_STYLE_RE,
    ROLE_ASSIGN_RE,
    ROUTE_RE,
    ROUTE_TIMEOUT_RE,
    RESTORE_RE,
    SCALE_RE,
    SECURITY_RE,
    SECURITY_SCOPE_RE,
    TOP_RE,
    UPDATE_RE,
    USER_SUBJECT_RE,
    VIEW_ROLE_RE,
    ADMIN_ROLE_RE,
    has_backup_restore_intent,
    has_certificate_monitor_intent,
    has_cluster_node_usage_intent,
    has_crash_loop_troubleshooting_intent,
    has_deployment_scaling_intent,
    has_doc_locator_intent,
    has_command_request,
    has_machine_config_reboot_intent,
    has_mco_concept_intent,
    has_node_drain_intent,
    has_openshift_kubernetes_compare_intent,
    has_operator_concept_intent,
    has_pod_lifecycle_concept_intent,
    has_pod_pending_troubleshooting_intent,
    has_project_finalizer_intent,
    has_project_scoped_rbac_intent,
    has_project_terminating_intent,
    has_rbac_assignment_intent,
    has_rbac_intent,
    has_route_ingress_compare_intent,
    has_update_doc_locator_intent,
    has_hosted_control_plane_signal,
    is_explainer_query,
    is_generic_intro_query,
)

# ambiguity / subquery 분해는 별도 모듈 구현을 그대로 재노출한다.
from .ambiguity import (
    has_follow_up_entity_ambiguity,
    has_logging_ambiguity,
    has_multiple_entity_ambiguity,
    has_security_doc_locator_ambiguity,
    has_update_doc_locator_ambiguity,
)
from .decompose import decompose_retrieval_queries
