"""Answer text façade.

실제 구현은 formatting/command shaping 모듈로 분리했다.
기존 import 경로는 유지하되, 새 코드가 실제 구현을 담당한다.
"""

from __future__ import annotations

from play_book_studio.retrieval import SessionContext

from .answer_text_commands import (
    align_answer_to_grounded_commands,
    build_deployment_scaling_answer,
    build_grounded_command_guide_answer,
    citation_marker,
    deployment_scaling_signal,
    extract_replica_counts,
    has_grounded_deployment_scale_citation,
    shape_actionable_ops_answer,
    shape_certificate_monitor_answer,
    shape_etcd_backup_answer,
    shape_pod_lifecycle_explainer,
    shape_pod_pending_troubleshooting,
    shape_project_termination_answer,
    shape_rbac_follow_up_answer,
)
from .answer_text_formatting import (
    ADJACENT_DUPLICATE_CITATION_RE,
    ACTIONABLE_GUIDE_QUERY_RE,
    ANSWER_CODE_BLOCK_RE,
    ANSWER_HEADER_RE,
    ANSWER_TABLE_BLOCK_RE,
    BARE_COMMAND_ANSWER_RE,
    CITATION_RE,
    GREETING_PREFIXES,
    GUIDE_HEADER_RE,
    INLINE_COMMAND_RE,
    INTRO_OFFTOPIC_SENTENCE_RE,
    NAMESPACE_ADMIN_QUERY_RE,
    REPLICA_COUNT_RE,
    RBAC_CLUSTER_ADMIN_DIFF_RE,
    RBAC_REVOKE_QUERY_RE,
    RBAC_VERIFY_QUERY_RE,
    RBAC_YAML_QUERY_RE,
    STRUCTURED_QUERY_RE,
    TRAILING_CITATIONS_RE,
    WEAK_GUIDE_TAIL_RE,
    ensure_korean_product_terms,
    normalize_answer_markup_blocks,
    normalize_answer_text,
    restore_readable_paragraphs,
    reshape_ops_answer_text,
    strip_intro_offtopic_noise,
    strip_structured_key_extra_guidance,
    strip_weak_additional_guidance,
    summarize_session_context,
    trim_productization_noise,
)

__all__ = [
    "ADJACENT_DUPLICATE_CITATION_RE",
    "ACTIONABLE_GUIDE_QUERY_RE",
    "ANSWER_CODE_BLOCK_RE",
    "ANSWER_HEADER_RE",
    "ANSWER_TABLE_BLOCK_RE",
    "BARE_COMMAND_ANSWER_RE",
    "CITATION_RE",
    "GREETING_PREFIXES",
    "GUIDE_HEADER_RE",
    "INLINE_COMMAND_RE",
    "INTRO_OFFTOPIC_SENTENCE_RE",
    "NAMESPACE_ADMIN_QUERY_RE",
    "REPLICA_COUNT_RE",
    "RBAC_CLUSTER_ADMIN_DIFF_RE",
    "RBAC_REVOKE_QUERY_RE",
    "RBAC_VERIFY_QUERY_RE",
    "RBAC_YAML_QUERY_RE",
    "STRUCTURED_QUERY_RE",
    "TRAILING_CITATIONS_RE",
    "WEAK_GUIDE_TAIL_RE",
    "SessionContext",
    "align_answer_to_grounded_commands",
    "build_deployment_scaling_answer",
    "build_grounded_command_guide_answer",
    "citation_marker",
    "deployment_scaling_signal",
    "ensure_korean_product_terms",
    "extract_replica_counts",
    "has_grounded_deployment_scale_citation",
    "normalize_answer_markup_blocks",
    "normalize_answer_text",
    "restore_readable_paragraphs",
    "reshape_ops_answer_text",
    "shape_actionable_ops_answer",
    "shape_certificate_monitor_answer",
    "shape_etcd_backup_answer",
    "shape_pod_lifecycle_explainer",
    "shape_pod_pending_troubleshooting",
    "shape_project_termination_answer",
    "shape_rbac_follow_up_answer",
    "strip_intro_offtopic_noise",
    "strip_structured_key_extra_guidance",
    "strip_weak_additional_guidance",
    "summarize_session_context",
    "trim_productization_noise",
]
